import React from 'react';

const Revision = () => {
  const dates = Array.from({ length: 30 }, (_, i) => i + 1);

  const getTasks = (date) => {
    const tasks = [];
    if (date === 15) tasks.push({ label: 'Bayes Rule', type: 'danger' });
    if (date % 4 === 0) tasks.push({ label: 'Math Review', type: 'success' });
    if (date === 22) tasks.push({ label: 'Mock Review', type: 'info' });
    return tasks;
  };

  return (
    <div>
      <header>
        <div>
          <h1>Revision Calendar</h1>
          <p className="subtitle">Spaced repetition schedule generated by the Adaptive Scheduler.</p>
        </div>
      </header>

      <div className="glass revision-panel">
        <div className="calendar-weekdays">
          <div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div>
        </div>
        <div className="calendar-grid">
          {dates.map(date => (
            <div key={date} className={`calendar-day ${date === 15 ? 'today' : ''}`}>
              <div className="calendar-date">{date}</div>
              <div className="calendar-tasks">
                {getTasks(date).map(task => (
                  <span key={`${date}-${task.label}`} className={`task-pill ${task.type}`}>
                    {task.label}
                  </span>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default Revision;
